/**
 * test_calculator - A simple calculator tool
 * 
 * Auto-generated by NEXUS Tool Forge
 * Generated at: 2026-03-22T17:33:42.765Z
 * 
 * @module tools/test_calculator
 */

/**
 * test_calculator - A simple calculator tool
 * Auto-generated by NEXUS Tool Forge
 */

export interface TestCalculatorInput {
  a: number; // First number
  b: number; // Second number
  operation: string; // Operation to perform
}

export interface TestCalculatorOutput {
  success: boolean;
  result?: unknown;
  error?: string;
}

export async function testCalculator(input: TestCalculatorInput): Promise<TestCalculatorOutput> {
  // Input validation
  if (input.a === undefined || input.a === null) {
    throw new Error(`a is required`);
  }
  if (input.b === undefined || input.b === null) {
    throw new Error(`b is required`);
  }
  if (!input.operation || !["add","subtract","multiply","divide"].includes(input.operation)) {
    throw new Error(`operation must be one of: add, subtract, multiply, divide`);
  }

  try {
  // Utility implementation
  return {
    success: true,
    result: input
  };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    };
  }
}

export default testCalculator;


// Tool metadata
export const metadata = {
  name: 'test_calculator',
  description: `A simple calculator tool`,
  createdAt: '2026-03-22T17:33:42.765Z',
  generatedBy: 'NEXUS Tool Forge'
};
